services:
  - type: web
    name: tectomark
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        value: tectomarksupport@gmail.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: "true"
      - key: SMTP_USER
        value: tectomarksupport@gmail.com
      - key: SMTP_PASS
        value: pzzcylzqlwtzxtnl
      - key: EMAIL_FROM
        value: "Tecto Mark <tectomarksupport@gmail.com>"
